### ISSUE TITLE
Add helm charts

### ISSUE THREAD

**Issue by zoriya** [zoriya/Kyoo#357]
### Feature description

Steps for scalling (pseudo related)
 - [x] Move sql migrations code out of the API (#358)
 - [ ] See how to handle meilisearch schema
 - [x] Split scanner fs-monitor and item scan (use rabbitmq work queue to sync them) (#410)
 - [ ] #579
 - [x] Use a named queue for autosync (right now, I think that two instances of autosync would try to update the external service twice) (#435)
 - [ ] #580
 - [ ] #581
 - [x] Use traefik as a reverse proxy (#450)

**Comment by bo0tzz** [comment]
For the [immich helm chart](https://github.com/immich-app/immich-charts), I used the [common-library](https://bjw-s.github.io/helm-charts/docs/common-library/) chart from bjw-s as a base, which helped get a chart together much quicker.

**Comment by onedr0p** [comment]
> Rather than 1 container doing all the transcoding, you could create 1 pod per transcode stream.

That _may_ require a Kubernetes operator or for the application to at least be Kubernetes aware and have proper RBAC setup for the app to create transcoding pods.

**Comment by bo0tzz** [comment]
I'm not particularly familiar with `HorizontalPodAutoscaler`s or KEDA, but maybe if one of those was involved scaling could be done without many changes on Kyoo's side?

**Comment by zoriya** [comment]
I do want to support transcoder scaling and distributed transcodes. Not sure what is needed for that, I just finished reading the getting started of k8s x)

**Comment by onedr0p** [comment]
Feel free to reach out if you need any help, I joined your discord 😄

**Comment by atmosx** [comment]
> > Rather than 1 container doing all the transcoding, you could create 1 pod per transcode stream.
> 
> That _may_ require a Kubernetes operator or for the application to at least be Kubernetes aware and have proper Kubernetes RBAC setup for the app to create transcoding pods. It would be neat but might be outside the scope of this issue.

For HPA an operator is not required. You can setup auto-scaling based on CPU metrics, which come out of the box with any modern k8s distribution. An operator handles way more than autoscaling (e.g. automated DB backups/restore, version upgrades, storage expansion, maintenance tasks, etc.)

**Comment by MegaShinySnivy** [comment]
I'd be willing to help test this chart and by extension Kyoo itself--I have enough users to put it through home/small event use (10ish users)

**Comment by zoriya** [comment]
Thanks! I started working on it on the `feat/helm` branch, but I was focused on something else, so It kinda stalled. An app-template based helm charts has been made by the folks in the home-assistant discord server.

I probably won't continue working on the helm chart soon, If someone wants to upstream the helm chart I'm open for it!

**Comment by acelinkio** [comment]
Hey @bo0tzz @onedr0p @joryirving @MegaShinySnivy , created a helm chart MR in #560. Take a look.  

`charts/README.md ` contains an example values file to deploy with no other resources.  Let me know if you have any questions or feedback.  Microservice helm charts can be a little challenging.  First pass focused on reducing configuration complexity.

**Comment by JeWe37** [comment]
It would be nice if as part of this one could also do something federation-esque and split the actual library storage across instances, but have it be shown as a single library.

**Comment by bo0tzz** [comment]
I don't really see how #477 relates to the helm chart

**Comment by JeWe37** [comment]
>  Route users to the same transcoder instance if they are requesting an video already being handled by an instance

From this it's a relatively small step architecturally towards "Route user towards the transcoder instance that has the file to be streamed locate close to it" essentially. It isn't too big a deal to have a slow distributed mount(think minio, s3fs, gluster, etc., even something simple like sshfs+mergerfs) for scanning, but it is bad for transcoding/streaming purposes.

**Comment by zoriya** [comment]
> Route users to the same transcoder instance if they are requesting an video already being handled by an instance

This would be needed to support replicate for the transcoder since using a redis for segment storage would probably introduce too much complexity & latency to make replicate worth it.

I have absolutely no idea how to do it tho

**Comment by JeWe37** [comment]
> > Route users to the same transcoder instance if they are requesting an video already being handled by an instance
> 
> This would be needed to support replicate for the transcoder since using a redis for segment storage would probably introduce too much complexity & latency to make replicate worth it.
> 
> I have absolutely no idea how to do it tho

I mean if this is all you need it's just a loadbalancer problem. HAProxy can do it using the [balance uri](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#4.2-balance%20url_param) config option probably. Couldn't find an equivalent strategy for traefik.

One of those(or some other load balancer, can't say I have a great overview of the options) could probably also be made to do "Route user towards the transcoder instance that has the file to be streamed located close to it" somehow, though I'd have to think how that might work.

**Comment by zoriya** [comment]
balence url is exactly what i was hoping to have. Thanks!

negotiation between replicas would indeed be good, it would be used to know when a user switch to another instance so the previous one can cleanup.

**Comment by JeWe37** [comment]
I was moreso thinking for negotiating which instance should take care of a request in the first place. Load might not map to number of simultaneous streams very well, for a small number of streams per instance. Think for instance a transcode to 4K HEVC vs 480p H264. Also would have the advantage of not pulling in a whole second proxy just for this.

**Comment by acelinkio** [comment]
@zoriya , can this ticket be updated like we talked about in https://github.com/zoriya/Kyoo/pull/560#issuecomment-2235422614.  Some of the related check boxes here were not relevant.  #450 did not need to happen for a helm chart to occur.  Kubernetes relies upon Ingress/Gateway standards for configuring reverse proxies of all kinds.

As for the other conversation, can that please move into #477,   That literally has nothing to do with the helm chart.  Personally I think the issue should be closed as they are asking for Kyoo cluster/mesh where one is in their home and the other is in the cloud somewhere.  I overwhelmingly disagree with any approach of using infrastructure to solve this problem.  You are relying upon infrastructure to solve issues that are bespoke problems.

**Comment by zoriya** [comment]
I created an issue for each item, i'll keep this list here for future reference. This isssue will be closed (and readme updated) when we merge the helm charts!
